-- replace with the Query ID you saw
SELECT * FROM TABLE(RESULT_SCAN('01bf9ae2-0106-9bf0-0014-4a5b00020226'));
select current_user();
SELECT t.$1
FROM @MY_S3_STAGE (FILE_FORMAT => 'demo_csv_fmt') t;
use schema DEMO_DB.PUBLIC;
COPY INTO DEMO_DB.PUBLIC.EMPLOYEE2
FROM '@MY_S3_STAGE/'
FILE_FORMAT = (TYPE = 'CSV')
VALIDATION_MODE = 'RETURN_ERRORS'
ON_ERROR = 'CONTINUE'
FORCE = TRUE;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    DATEADD(hour, -24, CURRENT_TIMESTAMP()),
    CURRENT_TIMESTAMP()
  )
)
WHERE TARGET_TABLE_NAME = 'EMPLOYEE'
ORDER BY START_TIME DESC
LIMIT 50;

create or replace TABLE DEMO_DB.PUBLIC.EMPLOYEE2 (
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	DOJ DATE
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.EMPLOYEE_REJECTS (
  raw_record VARCHAR,
  error_message VARCHAR,
  source_file VARCHAR,
  source_row INTEGER,
  load_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

drop table employee2;
COPY INTO DEMO_DB.PUBLIC.EMPLOYEE2
FROM '@MY_S3_STAGE/'
FILE_FORMAT = (TYPE = 'CSV')
VALIDATION_MODE = 'RETURN_ERRORS'
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) LIMIT 5;
-- then run the insert
INSERT INTO DEMO_DB.PUBLIC.EMPLOYEE_REJECTS (raw_record, error_message, source_file, source_row)
SELECT
  TO_VARCHAR(obj) AS raw_record,
  COALESCE(obj:"error"::string, obj:"message"::string, '') AS error_message,
  COALESCE(obj:"file"::string, obj:"source"::string, '') AS source_file,
  TRY_CAST(COALESCE(obj:"line"::string, obj:"row_number"::string, obj:"row"::string) AS INTEGER) AS source_row
FROM (
  SELECT OBJECT_CONSTRUCT(*) AS obj
  FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
);

CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.EMPLOYEE_REJECTS (
  PAYLOAD VARIANT,
  ERROR_MESSAGE VARCHAR(16777216),
  ERROR_CODE VARCHAR(16777216),
  SOURCE_FILE VARCHAR(16777216),
  SOURCE_ROW NUMBER(38,0),
  LOAD_TS TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

DESC TABLE DEMO_DB.PUBLIC.EMPLOYEE_REJECTS;

DESCRIBE PROCEDURE DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC; SHOW PROCEDURES IN SCHEMA DEMO_DB.PUBLIC LIKE 'COPY_TO_TABLE_PROC';




CREATE OR REPLACE PROCEDURE DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(
  SCHEMA_KEY VARCHAR
)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python==1.33.0','tabulate==0.9.0','cloudpickle==3.0.0')
IMPORTS = ('@dev_deployment/apps/DE_PROJECT_1/app.zip')
HANDLER = 'app.python.manual_procs.copy_to_table_proc';


DESCRIBE PROCEDURE DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR);  // signature = (SCHEMA_KEY VARCHAR)
SELECT GET_DDL('PROCEDURE','DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR)'); // CREATE OR REPLACE PROCEDURE "COPY_TO_TABLE_PROC"("SCHEMA_KEY" VARCHAR)
-- call the proc with the schema key
CALL DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC('emp_stg_schema_udemy');

-- immediately inspect COPY error rows returned by the COPY inside the proc
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- check persisted rejects (if helper inserted them)
SELECT * FROM DEMO_DB.PUBLIC.EMPLOYEE_REJECTS
ORDER BY LOAD_TS DESC
LIMIT 100;

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.PROCEDURES
WHERE object_name = 'COPY_TO_TABLE_PROC'
  AND object_schema = 'PUBLIC'
  AND object_database = 'DEMO_DB';


SHOW PROCEDURES IN SCHEMA DEMO_DB.PUBLIC;
DESCRIBE PROCEDURE DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR);
SELECT GET_DDL('PROCEDURE','DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR)');
SHOW GRANTS ON PROCEDURE DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR);

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.PROCEDURES
WHERE PROCEDURE_CATALOG = 'DEMO_DB'
  AND PROCEDURE_SCHEMA = 'PUBLIC'
  AND PROCEDURE_NAME = 'COPY_TO_TABLE_PROC'
  AND ARGUMENT_SIGNATURE = '(SCHEMA_KEY VARCHAR)';

  DROP PROCEDURE IF EXISTS DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR);

  SHOW PROCEDURES IN SCHEMA DEMO_DB.PUBLIC;

  DESCRIBE PROCEDURE DEMO_DB.PUBLIC.COPY_TO_TABLE_PROC(VARCHAR);
