SHOW GRANTS TO ROLE USERADMIN;
SHOW GRANTS TO ROLE CI_CD_ROLE;
SHOW GRANTS ON DATABASE DEMO_DB;
SHOW WAREHOUSES;
--SYSADMIN stuff
CREATE STAGE DEV_DEPLOYMENT;



--  USERADMIN stuff
use role useradmin;
GRANT READ ON STAGE demo_db.public.dev_deployment TO ROLE CI_CD_ROLE;
GRANT WRITE ON STAGE demo_db.public.dev_deployment TO ROLE CI_CD_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO USER ci_cd_user;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE CI_CD_ROLE;
GRANT USAGE ON SCHEMA demo_db.PUBLIC TO ROLE CI_CD_ROLE;
GRANT USAGE ON SCHEMA demo_db.PUBLIC TO ROLE CI_CD_ROLE;
GRANT CREATE STAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
-- 1. Create the role
CREATE ROLE ci_cd_role;

--2. Create User
CREATE USER ci_cd_user
  PASSWORD = 'Kr@k3n@dm1nDEA-Co2'  -- Replace with a secure value
  DEFAULT_ROLE = ci_cd_role
  DEFAULT_NAMESPACE = demo_db
  MUST_CHANGE_PASSWORD = FALSE;


SHOW DATABASES LIKE 'DEMO_DB';
SHOW SCHEMAS IN DATABASE DEMO_DB;


-- SECURITYADMIN stuff
-- 1. Grant usage on the database
GRANT USAGE ON DATABASE DEMO_DB TO ROLE ci_cd_role;

-- 3. Grant usage on all schemas in the database
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE ci_cd_role;

-- 4. Grant privileges on existing objects
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION ON SCHEMA DEMO_DB.PUBLIC TO ROLE ci_cd_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEMO_DB.PUBLIC TO ROLE ci_cd_role;

-- 5. Grant privileges on future objects
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DEMO_DB.PUBLIC TO ROLE ci_cd_role;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DEMO_DB.PUBLIC TO ROLE ci_cd_role;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DEMO_DB.PUBLIC TO ROLE ci_cd_role;

-- 6. (Optional) Assign the role to a user
GRANT ROLE ci_cd_role TO USER CI_CD_USER;
GRANT OWNERSHIP ON ROLE ci_cd_role TO ROLE SECURITYADMIN;

--7 Grant access to the data stage
GRANT USAGE ON STAGE DEMO_DB.PUBLIC.MY_S3_STAGE TO ROLE CI_CD_ROLE;

ALTER WAREHOUSE compute_wh SUSPEND;
drop role ci_cd_user;


-- added in debugging
-- DB / schema visibility
GRANT USAGE ON DATABASE DEMO_DB TO ROLE CI_CD_ROLE;
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;

-- Stage access (external stage or internal stage)
GRANT USAGE ON STAGE DEMO_DB.PUBLIC.MY_S3_STAGE TO ROLE CI_CD_ROLE;

-- Table privileges (target + reject)
GRANT INSERT, SELECT ON TABLE DEMO_DB.PUBLIC.EMPLOYEE2 TO ROLE CI_CD_ROLE;
GRANT INSERT, SELECT ON TABLE DEMO_DB.PUBLIC.EMPLOYEE_REJECTS TO ROLE CI_CD_ROLE;

-- Optional: allow role to create file formats / tables in the schema (if deployment must create them)
GRANT CREATE FILE FORMAT ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;

--- Added in debugging
-- run as ACCOUNTADMIN
-- 1) Enable imported privileges for the shared/imported SNOWFLAKE database
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE CI_CD_ROLE;

-- 2) Then grant access to the account_usage schema and its tables
GRANT USAGE ON SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE CI_CD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE CI_CD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE CI_CD_ROLE;

-- run as ACCOUNTADMIN in the consumer account
SHOW IMPORTED PRIVILEGES FOR DATABASE SNOWFLAKE;
SHOW GRANTS ON DATABASE SNOWFLAKE;
SHOW GRANTS TO ROLE CI_CD_ROLE;
SELECT CURRENT_ROLE(), CURRENT_USER();

-- just needed for the debugging issue
-- grant the role permission to use the file format
GRANT USAGE ON FILE FORMAT DEMO_DB.PUBLIC.DEBUG_CSV_FMT TO ROLE CI_CD_ROLE;
-----------------------------------------------
-- After a bunch of debugging the following was figured out (use next time from ACCOUNTADMIN)
-----------------------------------------------
-- file format usage
GRANT USAGE ON FILE FORMAT DEMO_DB.PUBLIC.DEBUG_CSV_FMT TO ROLE CI_CD_ROLE;

-- schema/db object privileges (if not already granted)
GRANT USAGE ON DATABASE DEMO_DB TO ROLE CI_CD_ROLE;
GRANT USAGE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DEMO_DB.PUBLIC TO ROLE CI_CD_ROLE;

-- account usage (if needed)
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE CI_CD_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE CI_CD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE CI_CD_ROLE;
